title: "Gladys Daniel"
name: "Gladys Daniel"
description: "Lead Technical Writer | Documentation Engineering | AI-assisted Documentation"
url: "https://gladysdanielt.github.io"
baseurl: "/documentation-portfolio"

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

locale: "en-US"
search: false

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

author:
  name: "Gladys Daniel"
  avatar: "/assets/images/gladys.jpeg"
  bio: "Information Architect"
  email: "gladys.tantepudi@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/gladysdanielt"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/tgladysdaniel/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/gladysdanielt"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/tgladysdaniel/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:gladys.tantepudi@gmail.com"

defaults:
  - scope:
      path: "_pages"
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false

include:
  - _pages

exclude:
  - samples/skill-changelog.md
